version: '3'
services:
  postgres-db:
    image: postgres:15
    container_name: postgres-db
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    restart: on-failure
    ports:
      - "5432:5432"
    volumes:
      - /root/postgres-data:/var/lib/postgresql/data

  telegram-bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: telegram-bot
    depends_on:
      - postgres-db
    restart: always
    environment:
      TG_TOKEN: ${TG_TOKEN}
      DB: ${DB}
      OPEN_AI_KEY: ${OPEN_AI_KEY}
    volumes:
      - .:/app
    command: ["python", "bot.py"]

volumes:
  postgres-data:
