version: '3'
services:
  postgres:
    image: postgres
    container_name: postgres-db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5433:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  telegram-bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: telegram-bot
    depends_on:
      - postgres
    environment:
      TG_TOKEN: ${TG_TOKEN}
      DB: ${DB}
      OPEN_AI_KEY: ${OPEN_AI_KEY}
    volumes:
      - .:/app
    command: ["python", "bot.py"]

volumes:
  postgres-data: